import React, { Component } from 'react'
import PeriodicTableRow from '../components/PeriodicTableRow'

import './PeriodicTable.css'
const elements =
    [
        {
            "atomicNumber": 1,
            "element": "H",
            "elementName": "Hidrogênio",
            "type": "noMetal",
            "family": 1,
            "period": 1,
        },
        {
            "atomicNumber": 2,
            "element": "He",
            "elementName": "Hélio",
            "type": "nobleGases",
            "family": 18,
            "period": 1,
        },
        {
            "atomicNumber": 3,
            "element": "Li",
            "elementName": "Lítio",
            "type": "alkaliMetals",
            "family": 1,
            "period": 2,
        },
        {
            "atomicNumber": 4,
            "element": "Be",
            "elementName": "Berílio",
            "type": "alkalineEarthMetals",
            "family": 2,
            "period": 2,
        },
        {
            "atomicNumber": 5,
            "element": "B",
            "elementName": "Boro",
            "type": "semiMetals",
            "family": 13,
            "period": 2,
        },
        {
            "atomicNumber": 6,
            "element": "C",
            "elementName": "Carbono",
            "type": "noMetal",
            "family": 14,
            "period": 2,
        },
        {
            "atomicNumber": 7,
            "element": "N",
            "elementName": "Nitrogênio",
            "type": "noMetal",
            "family": 15,
            "period": 2,
        },
        {
            "atomicNumber": 8,
            "element": "O",
            "elementName": "Oxigênio",
            "type": "noMetal",
            "family": 16,
            "period": 2,
        },
        {
            "atomicNumber": 9,
            "element": "F",
            "elementName": "Fluor",
            "type": "halogens",
            "family": 17,
            "period": 2,
        },
        {
            "atomicNumber": 10,
            "element": "Ne",
            "elementName": "Neônio",
            "type": "nobleGases",
            "family": 18,
            "period": 2,
        },
        {
            "atomicNumber": 11,
            "element": "Na",
            "elementName": "Sódio",
            "type": "alkaliMetals",
            "family": 1,
            "period": 3,
        },
        {
            "atomicNumber": 12,
            "element": "Mg",
            "elementName": "Magnésio",
            "type": "alkalineEarthMetals",
            "family": 2,
            "period": 3,
        },
        {
            "atomicNumber": 13,
            "element": "Al",
            "elementName": "Alumínio",
            "type": "otherMetals",
            "family": 13,
            "period": 3,
        },
        {
            "atomicNumber": 14,
            "element": "Si",
            "elementName": "Silício",
            "type": "semiMetals",
            "family": 14,
            "period": 3,
        },
        {
            "atomicNumber": 15,
            "element": "P",
            "elementName": "Fósforo",
            "type": "noMetal",
            "family": 15,
            "period": 3,
        },
        {
            "atomicNumber": 16,
            "element": "S",
            "elementName": "Enxofre",
            "type": "noMetal",
            "family": 16,
            "period": 3,
        },
        {
            "atomicNumber": 17,
            "element": "Cl",
            "elementName": "Cloro",
            "type": "halogens",
            "family": 17,
            "period": 3,
        },
        {
            "atomicNumber": 18,
            "element": "Ar",
            "elementName": "Argônio",
            "type": "nobleGases",
            "family": 18,
            "period": 3,
        },
        {
            "atomicNumber": 19,
            "element": "K",
            "elementName": "Potássio",
            "type": "alkaliMetals",
            "family": 1,
            "period": 4,
        },
        {
            "atomicNumber": 20,
            "element": "Ca",
            "elementName": "Cálcio",
            "type": "alkalineEarthMetals",
            "family": 2,
            "period": 4,
        },
        {
            "atomicNumber": 21,
            "element": "Sc",
            "elementName": "Escândio",
            "type": "transitionMetals",
            "family": 3,
            "period": 4,
        },
        {
            "atomicNumber": 22,
            "element": "Ti",
            "elementName": "Titânio",
            "type": "transitionMetals",
            "family": 4,
            "period": 4,
        },
        {
            "atomicNumber": 23,
            "element": "V",
            "elementName": "Vanádio",
            "type": "transitionMetals",
            "family": 5,
            "period": 4,
        },
        {
            "atomicNumber": 24,
            "element": "Cr",
            "elementName": "Cromo",
            "type": "transitionMetals",
            "family": 6,
            "period": 4,
        },
        {
            "atomicNumber": 25,
            "element": "Mn",
            "elementName": "Manganês",
            "type": "transitionMetals",
            "family": 7,
            "period": 4,
        },
        {
            "atomicNumber": 26,
            "element": "Fe",
            "elementName": "Ferro",
            "type": "transitionMetals",
            "family": 8,
            "period": 4,
        },
        {
            "atomicNumber": 27,
            "element": "Co",
            "elementName": "Hidrogênio",
            "type": "transitionMetals",
            "family": 9,
            "period": 4,
        },
        {
            "atomicNumber": 28,
            "element": "Ni",
            "elementName": "Cobalto",
            "type": "transitionMetals",
            "family": 10,
            "period": 4,
        },
        {
            "atomicNumber": 29,
            "element": "Cu",
            "elementName": "Níquel",
            "type": "transitionMetals",
            "family": 11,
            "period": 4,
        },
        {
            "atomicNumber": 30,
            "element": "Zn",
            "elementName": "Zinco",
            "type": "transitionMetals",
            "family": 12,
            "period": 4,
        },
        {
            "atomicNumber": 31,
            "element": "Ga",
            "elementName": "Gálio",
            "type": "otherMetals",
            "family": 13,
            "period": 4,
        },
        {
            "atomicNumber": 32,
            "element": "Ge",
            "elementName": "Germânio",
            "type": "semiMetals",
            "family": 14,
            "period": 4,
        },
        {
            "atomicNumber": 33,
            "element": "As",
            "elementName": "Arsênio",
            "type": "semiMetals",
            "family": 15,
            "period": 4,
        },
        {
            "atomicNumber": 34,
            "element": "Se",
            "elementName": "Selênio",
            "type": "noMetal",
            "family": 16,
            "period": 4,
        },
        {
            "atomicNumber": 35,
            "element": "Br",
            "elementName": "Bromo",
            "type": "halogens",
            "family": 17,
            "period": 4,
        },
        {
            "atomicNumber": 36,
            "element": "Kr",
            "elementName": "Criptônio",
            "type": "nobleGases",
            "family": 18,
            "period": 4,
        },
        {
            "atomicNumber": 37,
            "element": "Rb",
            "elementName": "Rubídio",
            "type": "alkaliMetals",
            "family": 1,
            "period": 5,
        },
        {
            "atomicNumber": 38,
            "element": "Sr",
            "elementName": "Estrôncio",
            "type": "alkalineEarthMetals",
            "family": 2,
            "period": 5,
        },
        {
            "atomicNumber": 39,
            "element": "Y",
            "elementName": "Ítrio",
            "type": "transitionMetals",
            "family": 3,
            "period": 5,
        },
        {
            "atomicNumber": 40,
            "element": "Zr",
            "elementName": "Zircônio",
            "type": "transitionMetals",
            "family": 4,
            "period": 5,
        },
        {
            "atomicNumber": 41,
            "element": "Nb",
            "elementName": "Nióbio",
            "type": "transitionMetals",
            "family": 5,
            "period": 5,
        },
        {
            "atomicNumber": 42,
            "element": "Mo",
            "elementName": "Molibdênio",
            "type": "transitionMetals",
            "family": 6,
            "period": 5,
        },
        {
            "atomicNumber": 43,
            "element": "Tc",
            "elementName": "Tecnécio",
            "type": "transitionMetals",
            "family": 7,
            "period": 5,
        },
        {
            "atomicNumber": 44,
            "element": "Ru",
            "elementName": "Rutênio",
            "type": "transitionMetals",
            "family": 8,
            "period": 5,
        },
        {
            "atomicNumber": 45,
            "element": "Rh",
            "elementName": "Ródio",
            "type": "transitionMetals",
            "family": 9,
            "period": 5,
        },
        {
            "atomicNumber": 46,
            "element": "Pd",
            "elementName": "Paládio",
            "type": "transitionMetals",
            "family": 10,
            "period": 5,
        },
        {
            "atomicNumber": 47,
            "element": "Ag",
            "elementName": "Prata",
            "type": "transitionMetals",
            "family": 11,
            "period": 5,
        },
        {
            "atomicNumber": 48,
            "element": "Cd",
            "elementName": "Cádmio",
            "type": "transitionMetals",
            "family": 12,
            "period": 5,
        },
        {
            "atomicNumber": 49,
            "element": "In",
            "elementName": "Índio",
            "type": "otherMetals",
            "family": 13,
            "period": 5,
        },
        {
            "atomicNumber": 50,
            "element": "Sn",
            "elementName": "Estanho",
            "type": "otherMetals",
            "family": 14,
            "period": 5,
        },
        {
            "atomicNumber": 51,
            "element": "Sb",
            "elementName": "Antimônio",
            "type": "semiMetals",
            "family": 15,
            "period": 5,
        },
        {
            "atomicNumber": 52,
            "element": "Te",
            "elementName": "Telúrio",
            "type": "semiMetals",
            "family": 16,
            "period": 5,
        },
        {
            "atomicNumber": 53,
            "element": "I",
            "elementName": "Iodo",
            "type": "halogens",
            "family": 17,
            "period": 5,
        },
        {
            "atomicNumber": 54,
            "element": "Xe",
            "elementName": "Xenônio",
            "type": "nobleGases",
            "family": 18,
            "period": 5,
        },
        {
            "atomicNumber": 55,
            "element": "Cs",
            "elementName": "Césio",
            "type": "alkaliMetals",
            "family": 1,
            "period": 6,
        },
        {
            "atomicNumber": 56,
            "element": "Ba",
            "elementName": "Bário",
            "type": "alkalineEarthMetals",
            "family": 2,
            "period": 6,
        },
        {
            "atomicNumber": "57-71",
            "element": "",
            "elementName": "",
            "type": "",
            "family": 3,
            "period": 6,
        },
        {
            "atomicNumber": 57,
            "element": "La",
            "elementName": "Latânio",
            "type": "lanthanides",
            "family": 4,
        },
        {
            "atomicNumber": 58,
            "element": "Ce",
            "elementName": "Cério",
            "type": "lanthanides",
            "family": 5,
            "period": 6,
        },
        {
            "atomicNumber": 59,
            "element": "Pr",
            "elementName": "Praseodímio",
            "type": "lanthanides",
            "family": 6,
            "period": 6,
        },
        {
            "atomicNumber": 60,
            "element": "Nd",
            "elementName": "Neodímio",
            "type": "lanthanides",
            "family": 7,
            "period": 6,
        },
        {
            "atomicNumber": 61,
            "element": "Pm",
            "elementName": "Promécio",
            "type": "lanthanides",
            "family": 8,
            "period": 6,
        },
        {
            "atomicNumber": 62,
            "element": "Sm",
            "elementName": "Samário",
            "type": "lanthanides",
            "family": 9,
            "period": 6,
        },
        {
            "atomicNumber": 63,
            "element": "Eu",
            "elementName": "Európio",
            "type": "lanthanides",
            "family": 10,
            "period": 6,
        },
        {
            "atomicNumber": 64,
            "element": "Gd",
            "elementName": "Gadolínio",
            "type": "lanthanides",
            "family": 11,
            "period": 6,
        },
        {
            "atomicNumber": 65,
            "element": "Tb",
            "elementName": "Térbio",
            "type": "lanthanides",
            "family": 12,
            "period": 6,
        },
        {
            "atomicNumber": 66,
            "element": "Dy",
            "elementName": "Disprósio",
            "type": "lanthanides",
            "family": 13,
            "period": 6,
        },
        {
            "atomicNumber": 67,
            "element": "Ho",
            "elementName": "Hólmio",
            "type": "lanthanides",
            "family": 14,
            "period": 6,
        },
        {
            "atomicNumber": 68,
            "element": "Er",
            "elementName": "Érbio",
            "type": "lanthanides",
            "family": 15,
            "period": 6,
        },
        {
            "atomicNumber": 69,
            "element": "Tm",
            "elementName": "Túlio",
            "type": "lanthanides",
            "family": 16,
            "period": 6,
        },
        {
            "atomicNumber": 70,
            "element": "Yb",
            "elementName": "Itérbio",
            "type": "lanthanides",
            "family": 17,
            "period": 6,
        },
        {
            "atomicNumber": 71,
            "element": "Lu",
            "elementName": "Lutécio",
            "type": "lanthanides",
            "family": 18,
            "period": 6,
        },
        {
            "atomicNumber": 72,
            "element": "Hf",
            "elementName": "Háfnio",
            "type": "transitionMetals",
            "family": 4,
            "period": 6,
        },
        {
            "atomicNumber": 73,
            "element": "Ta",
            "elementName": "Tântalo",
            "type": "transitionMetals",
            "family": 5,
            "period": 6,
        },
        {
            "atomicNumber": 74,
            "element": "W",
            "elementName": "Tungstênio",
            "type": "transitionMetals",
            "family": 6,
            "period": 6,
        },
        {
            "atomicNumber": 75,
            "element": "Re",
            "elementName": "Rênio",
            "type": "transitionMetals",
            "family": 7,
            "period": 6,
        },
        {
            "atomicNumber": 76,
            "element": "Os",
            "elementName": "Ósmio",
            "type": "transitionMetals",
            "family": 8,
            "period": 6,
        },
        {
            "atomicNumber": 77,
            "element": "Ir",
            "elementName": "Irídio",
            "type": "transitionMetals",
            "family": 9,
            "period": 6,
        },
        {
            "atomicNumber": 78,
            "element": "Pt",
            "elementName": "Platina",
            "type": "transitionMetals",
            "family": 10,
            "period": 6,
        },
        {
            "atomicNumber": 79,
            "element": "Au",
            "elementName": "Ouro",
            "type": "transitionMetals",
            "family": 11,
            "period": 6,
        },
        {
            "atomicNumber": 80,
            "element": "Hg",
            "elementName": "Mercúrio",
            "type": "transitionMetals",
            "family": 12,
            "period": 6,
        },
        {
            "atomicNumber": 81,
            "element": "Tl",
            "elementName": "Tálio",
            "type": "otherMetals",
            "family": 13,
            "period": 6,
        },
        {
            "atomicNumber": 82,
            "element": "Pb",
            "elementName": "Chumbo",
            "type": "otherMetals",
            "family": 14,
            "period": 6,
        },
        {
            "atomicNumber": 83,
            "element": "Bi",
            "elementName": "Bismuto",
            "type": "otherMetals",
            "family": 15,
            "period": 6,
        },
        {
            "atomicNumber": 84,
            "element": "Po",
            "elementName": "Polônio",
            "type": "semiMetals",
            "family": 16,
            "period": 6,
        },
        {
            "atomicNumber": 85,
            "element": "At",
            "elementName": "Ástato",
            "type": "halogens",
            "family": 17,
            "period": 6,
        },
        {
            "atomicNumber": 86,
            "element": "Rn",
            "elementName": "Radônio",
            "type": "nobleGases",
            "family": 18,
            "period": 6,
        },
        {
            "atomicNumber": 87,
            "element": "Fr",
            "elementName": "Frâncio",
            "type": "alkaliMetals",
            "family": 1,
            "period": 7,
        },
        {
            "atomicNumber": 88,
            "element": "Ra",
            "elementName": "Rádio",
            "type": "alkalineEarthMetals",
            "family": 2,
            "period": 7,
        },
        {
            "atomicNumber": "89-103",
            "element": "",
            "elementName": "",
            "type": "",
            "family": 3,
            "period": 7,
        },
        {
            "atomicNumber": 89,
            "element": "Ac",
            "elementName": "Actínio",
            "type": "actinides",
            "family": 4,
            "period": 7,
        },
        {
            "atomicNumber": 90,
            "element": "Th",
            "elementName": "Tório",
            "type": "actinides",
            "family": 5,
            "period": 7,
        },
        {
            "atomicNumber": 91,
            "element": "Pa",
            "elementName": "Protactínio",
            "type": "actinides",
            "family": 6,
            "period": 7,
        },
        {
            "atomicNumber": 92,
            "element": "U",
            "elementName": "Urânio",
            "type": "actinides",
            "family": 7,
            "period": 7,
        },
        {
            "atomicNumber": 93,
            "element": "Np",
            "elementName": "Netúnio",
            "type": "actinides",
            "family": 8,
            "period": 7,
        },
        {
            "atomicNumber": 94,
            "element": "Pu",
            "elementName": "Plutônio",
            "type": "actinides",
            "family": 9,
            "period": 7,
        },
        {
            "atomicNumber": 95,
            "element": "Am",
            "elementName": "Amercício",
            "type": "actinides",
            "family": 10,
            "period": 7,
        },
        {
            "atomicNumber": 96,
            "element": "Cm",
            "elementName": "Cúrio",
            "type": "actinides",
            "family": 11,
            "period": 7,
        },
        {
            "atomicNumber": 97,
            "element": "Bk",
            "elementName": "Berquélio",
            "type": "actinides",
            "family": 12,
            "period": 7,
        },
        {
            "atomicNumber": 98,
            "element": "Cf",
            "elementName": "Califórnio",
            "type": "actinides",
            "family": 13,
            "period": 7,
        },
        {
            "atomicNumber": 99,
            "element": "Es",
            "elementName": "Einsténio",
            "type": "actinides",
            "family": 14,
            "period": 7,
        },
        {
            "atomicNumber": 100,
            "element": "Fm",
            "elementName": "Férmio",
            "type": "actinides",
            "family": 15,
            "period": 7,
        },
        {
            "atomicNumber": 101,
            "element": "Md",
            "elementName": "Mendelévio",
            "type": "actinides",
            "family": 16,
            "period": 7,
        },
        {
            "atomicNumber": 102,
            "element": "No",
            "elementName": "Nobélio",
            "type": "actinides",
            "family": 17,
            "period": 7,
        },
        {
            "atomicNumber": 103,
            "element": "Lr",
            "elementName": "Laurêncio",
            "type": "actinides",
            "family": 18,
            "period": 7,
        },
        {
            "atomicNumber": 104,
            "element": "Rf",
            "elementName": "Rutherfórdio",
            "type": "transitionMetals",
            "family": 4,
            "period": 7,
        },
        {
            "atomicNumber": 105,
            "element": "Db",
            "elementName": "Dúbnio",
            "type": "transitionMetals",
            "family": 5,
            "period": 7,
        },
        {
            "atomicNumber": 106,
            "element": "Sg",
            "elementName": "Seabórgio",
            "type": "transitionMetals",
            "family": 6,
            "period": 7,
        },
        {
            "atomicNumber": 107,
            "element": "Bh",
            "elementName": "Bóhrio",
            "type": "transitionMetals",
            "family": 7,
            "period": 7,
        },
        {
            "atomicNumber": 108,
            "element": "Hs",
            "elementName": "Hássio",
            "type": "transitionMetals",
            "family": 8,
            "period": 7,
        },
        {
            "atomicNumber": 109,
            "element": "Mt",
            "elementName": "Meitnério",
            "type": "transitionMetals",
            "family": 9,
            "period": 7,
        },
        {
            "atomicNumber": 110,
            "element": "Ds",
            "elementName": "Darmstádio",
            "type": "transitionMetals",
            "family": 10,
            "period": 7,
        },
        {
            "atomicNumber": 111,
            "element": "Rg",
            "elementName": "Roentgênio",
            "type": "transitionMetals",
            "family": 11,
            "period": 7,
        },
        {
            "atomicNumber": 112,
            "element": "Cn",
            "elementName": "Copernício",
            "type": "transitionMetals",
            "family": 12,
            "period": 7,
        },
        {
            "atomicNumber": 113,
            "element": "Nh",
            "elementName": "Nihônio",
            "type": "otherMetals",
            "family": 13,
            "period": 7,
        },
        {
            "atomicNumber": 114,
            "element": "Fl",
            "elementName": "Fleróvio",
            "type": "otherMetals",
            "family": 14,
            "period": 7,
        },
        {
            "atomicNumber": 115,
            "element": "Mc",
            "elementName": "Moscóvio",
            "type": "otherMetals",
            "family": 15,
            "period": 7,
        },
        {
            "atomicNumber": 116,
            "element": "Lv",
            "elementName": "Livermório",
            "type": "otherMetals",
            "family": 16,
            "period": 7,
        },
        {
            "atomicNumber": 117,
            "element": "Ts",
            "elementName": "Tenessino",
            "type": "halogens",
            "family": 17,
            "period": 7,
        },
        {
            "atomicNumber": 118,
            "element": "Og",
            "elementName": "Oganessônio",
            "type": "nobleGases",
            "family": 18,
            "period": 7,
        },
    ]

    
const printRow = element => element

export default class PeriodicTable extends Component {

    

    render() {
        return (
            <div className='periodic-table'>
                <PeriodicTableRow elements={elements.map(printRow)} key="pOne" />
            </div>
        )
    }
}